# site settings
title: Mitch Mancuso
subtitle: Portfolio
description: A site for coding projects and portfolio items.
baseurl: ""
url:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/mitchmancuso
linkedin_url: https://linkedin.com/in/mmancuso8

# build settings
markdown: kramdown

sass:
  style: compressed
